/// Generated By XFlutter Cli.
/// 
/// more info: https://xflutter-cli.aghiadodeh.com
import 'package:get_it/get_it.dart';
import 'package:isar/isar.dart';

/// Generic [Isar] CRUD.
///
/// [T] is the generic model,
/// [ID] is the Primary-Key type like [String] or [int]
abstract class IsarBaseDataSource<T, ID> {
  Isar get isar => GetIt.I.get<Isar>();

  /// fetch [T] object from local-database
  T? findOne(ID? id);

  /// fetch cached [T] list with pagination from local-database
  List<T> findByPage(int page, {Map<String, dynamic> filters = const {}});

  /// fetch cached [T] list without pagination from local-database
  List<T> findAll({Map<String, dynamic> filters = const {}});

  /// add/update [T] into local-database
  void insert(T item);

  /// save list of [T] in local-database
  void insertAll(List<T> data);

  /// delete [T] from local-database
  void delete(ID? id);
}

