/// Generated By XFlutter Cli.
///
/// more info: https://xflutter-cli.aghiadodeh.com
import 'package:flutter/material.dart';
import 'package:xflutter_cli_example/config/instance_config.dart';
import 'package:xflutter_cli_example/controllers/theme_controller.dart';

extension ThemeUtils on ThemeData {
  /// get current theme textColor
  Color? get textColor => textTheme.bodyText1?.color;

  /// if applied theme is dark theme
  bool isDark() => findInstance<ThemeController>().themeMode.value == ThemeMode.dark;
}
