/// Generated By XFlutter Cli.
///
/// more info: https://xflutter-cli.aghiadodeh.com
import 'package:flutter/material.dart';
import '../ui/widgets/animations/animated_gesture.dart';
import '../ui/widgets/animations/customized_animated_widget.dart';

extension WidgetUtils on Widget {
  /// animate [Widget] on appear
  Widget withAnimation({double from = 30}) {
    return CustomizedAnimatedWidget(from: from, child: this);
  }

  /// set same width and height to [Widget]
  Widget size(double size) {
    return SizedBox(width: size, height: size, child: this);
  }

  /// set width and height to [Widget]
  Widget withSize({required double width, required double height}) {
    return SizedBox(width: width, height: height, child: this);
  }

  /// set width to [Widget]
  Widget width(double width) {
    return SizedBox(width: width, child: this);
  }

  /// set height to [Widget]
  Widget height(double height) {
    return SizedBox(height: height, child: this);
  }

  /// wrap [Widget] inside [GestureDetector]
  Widget onClick(VoidCallback callback) {
    return GestureDetector(
      onTap: callback,
      child: this,
    );
  }

  /// wrap [Widget] inside [GestureDetector]
  Widget onClickWithAnimation(VoidCallback callback) {
    return AnimatedGesture(
      callback: callback,
      child: this,
    );
  }

  /// wrap [Widget] inside [Padding]
  Widget padding(EdgeInsets edgeInsets) {
    return Padding(padding: edgeInsets, child: this);
  }
}

/// [function] immediately will be called once upon screen has finishes rendering the layout
void runAfterBuild(Function() function) {
  WidgetsBinding.instance.addPostFrameCallback((_) => function());
}
