/// Generated By XFlutter Cli.
///
/// more info: https://xflutter-cli.aghiadodeh.com

import 'package:get_it/get_it.dart';
import 'utils/isar_utils.dart';
import 'package:isar/isar.dart';

class AppIsar {
  /// initialize new [Isar] instance and make it singleton.
  static Future<void> initialize() async {
    final instance = await openIsar();
    GetIt.I.registerLazySingleton<Isar>(() => instance);
  }
}
