/// Generated By XFlutter Cli.
/// 
/// more info: https://xflutter-cli.aghiadodeh.com
import 'package:flutter/material.dart';
import 'flex_utils.dart';

class FlexBuilder extends StatelessWidget {
  final Widget Function(
    /// screen size
    Size size,

    /// [FlexSize] of device screen
    FlexSize flexSize,
  ) builder;
  const FlexBuilder({required this.builder, Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final size = MediaQuery.of(context).size;
    return builder.call(size, flexSize);
  }
}
