/// Generated By XFlutter Cli.
/// 
/// more info: https://xflutter-cli.aghiadodeh.com
import 'package:flutter/material.dart';
import 'flex_dimensions.dart';

class FlexEdgeInsets extends EdgeInsets {
  FlexEdgeInsets.all(FlexDiemension diemension) : super.all(diemension.value);

  FlexEdgeInsets.symmetric({
    FlexDiemension? horizontal,
    FlexDiemension? vertical,
  }) : super.symmetric(horizontal: horizontal?.value ?? 0, vertical: vertical?.value ?? 0);

  FlexEdgeInsets.fromLTRB({
    FlexDiemension? left,
    FlexDiemension? top,
    FlexDiemension? right,
    FlexDiemension? bottom,
  }) : super.fromLTRB(left?.value ?? 0, top?.value ?? 0, right?.value ?? 0, bottom?.value ?? 0);

  FlexEdgeInsets.only({
    FlexDiemension? left,
    FlexDiemension? top,
    FlexDiemension? right,
    FlexDiemension? bottom,
  }) : super.only(left: left?.value ?? 0, top: top?.value ?? 0, right: right?.value ?? 0, bottom: bottom?.value ?? 0);
}

class FlexEdgeInsetsDirectional extends EdgeInsetsDirectional {
  FlexEdgeInsetsDirectional.all(FlexDiemension diemension) : super.all(diemension.value);

  FlexEdgeInsetsDirectional.fromSTEB({
    FlexDiemension? start,
    FlexDiemension? top,
    FlexDiemension? end,
    FlexDiemension? bottom,
  }) : super.fromSTEB(start?.value ?? 0, top?.value ?? 0, end?.value ?? 0, bottom?.value ?? 0);

  FlexEdgeInsetsDirectional.only({
    FlexDiemension? start,
    FlexDiemension? top,
    FlexDiemension? end,
    FlexDiemension? bottom,
  }) : super.only(start: start?.value ?? 0, top: top?.value ?? 0, end: end?.value ?? 0, bottom: bottom?.value ?? 0);
}
