/// Generated By XFlutter Cli.
///
/// more info: https://xflutter-cli.aghiadodeh.com

import '../models/user/user.dart';
import 'package:isar/isar.dart';
import 'package:path_provider/path_provider.dart';
import '../../network/config/env.dart';

/// Open a new [Isar] instance.
Future<Isar> openIsar() async {
  final directory = await getApplicationDocumentsDirectory();
  final isar = await Isar.open(
    [
      IsarUserSchema,
    ],
    directory: directory.path,
  );
  return isar;
}

/// get limitation offset depending on [Env.perPage] and selected [page]
int offset(page) => ((Env.perPage * page) - Env.perPage).toInt();

/// FNV-1a 64bit hash algorithm optimized for Dart Strings
int fastHash(String? id) {
  final string = id ?? DateTime.now().toIso8601String();
  var hash = 0xcbf29ce484222325;

  var i = 0;
  while (i < string.length) {
    final codeUnit = string.codeUnitAt(i++);
    hash ^= codeUnit >> 8;
    hash *= 0x100000001b3;
    hash ^= codeUnit & 0xFF;
    hash *= 0x100000001b3;
  }

  return hash;
}
