/// Generated By XFlutter Cli.
///
/// more info: https://xflutter-cli.aghiadodeh.com

import 'package:isar/isar.dart';
import 'package:xflutter_cli_example/models/data_models.dart';
part 'product.g.dart';

@collection
class IsarProduct {
  Id? isarId;
  @Index(unique: true, replace: true)
  int? id;
  String? title;
  String? description;
  double? price;
  double? discountPercentage;
  double? rating;
  double? stock;
  String? brand;
  String? category;
  String? thumbnail;
  List<String?>? images;

  IsarProduct({
    this.isarId,
    this.id,
    this.title,
    this.description,
    this.price,
    this.discountPercentage,
    this.rating,
    this.stock,
    this.brand,
    this.category,
    this.thumbnail,
    this.images,
  });
}

extension IsarProductUtils on IsarProduct {
  Product fromIsar() {
    return Product(
      id: id,
      title: title,
      description: description,
      price: price,
      discountPercentage: discountPercentage,
      rating: rating,
      stock: stock,
      brand: brand,
      category: category,
      thumbnail: thumbnail,
      images: images,
    );
  }
}

extension ProductUtils on Product {
  IsarProduct toIsar() {
    return IsarProduct(
      id: id,
      title: title,
      description: description,
      price: num.tryParse(price.toString())?.toDouble(),
      discountPercentage: num.tryParse(discountPercentage.toString())?.toDouble(),
      rating: num.tryParse(rating.toString())?.toDouble(),
      stock: num.tryParse(stock.toString())?.toDouble(),
      brand: brand,
      category: category,
      thumbnail: thumbnail,
      images: images,
    );
  }
}
