/// Generated By XFlutter Cli.
///
/// more info: https://xflutter-cli.aghiadodeh.com
import 'package:flutter/material.dart';
import 'package:flutterx_live_data/flutterx_live_data.dart';
import 'package:xflutter_cli_example/ui/widgets/text_fields/livedata_text_field.dart';
import 'package:xflutter_cli_example/ui/widgets/buttons/customized_button.dart';
import 'package:xflutter_cli_example/ui/resources/dimensions/dimensions.dart';
import 'package:xflutter_cli_example/models/forms/formz_email.dart';
import 'package:xflutter_cli_example/models/forms/formz_password.dart';

import "package:xflutter_cli_example/ui/widgets/instance/instance_builder.dart";
import "../viewmodels/login_viewmodel.dart";
import 'package:xflutter_cli_example/ui/core/layouts/theme_widget.dart';

class LoginForm extends StatelessWidget {
  const LoginForm({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return InstanceBuilder<LoginViewModel>(
      builder: (viewModel) {
        return ThemeWidget(
          builder: (context, theme) {
            return Column(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                Column(
                  children: [
                    ///// Login Mail /////
                    LiveDataTextField<FormzEmail>(
                      label: 'mail',
                      liveData: viewModel.params.mail,
                      onTextChanged: viewModel.formzEmailChanged,
                      errorText: () => viewModel.params.mail.value.error?.message,
                      keyboardType: TextInputType.emailAddress,
                    ),
                    const SizedBox(height: formSpacing),

                    ///// Login Password /////
                    LiveDataTextField<FormzPassword>(
                      label: 'password',
                      liveData: viewModel.params.password,
                      onTextChanged: viewModel.formzPasswordChanged,
                      errorText: () => viewModel.params.password.value.error?.message,
                      obscureText: true,
                    ),
                    const SizedBox(height: formSpacing),
                  ],
                ),

                ///// Form Submit /////
                LiveDataBuilder<bool>(
                  data: viewModel.baseParams.loading,
                  builder: (context, boolean) {
                    return SizedBox(
                      width: double.infinity,
                      child: CustomizedButton(
                        enabled: !boolean,
                        callback: viewModel.login,
                        child: const Text("Submit"),
                      ),
                    );
                  },
                ),
              ],
            );
          },
        );
      },
    );
  }
}
