/// Generated By XFlutter Cli.
///
/// more info: https://xflutter-cli.aghiadodeh.com
import 'package:flutter/material.dart';
import 'package:xflutter_cli_example/ui/core/layouts/base_scroll_view.dart';
import 'package:xflutter_cli_example/ui/resources/dimensions/dimensions.dart';
import "package:xflutter_cli_example/ui/widgets/instance/instance_builder.dart";
import "../viewmodels/login_viewmodel.dart";
import 'package:xflutter_cli_example/ui/core/layouts/theme_widget.dart';
import '../widgets/login_form.dart';

class LoginTabletScreen extends StatelessWidget {
  const LoginTabletScreen({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return InstanceBuilder<LoginViewModel>(
      builder: (viewModel) => ThemeWidget(
        builder: (context, theme) => const BaseScrollView(
          child: Padding(
            padding: EdgeInsets.symmetric(horizontal: fourUnits, vertical: threeUnits),
            child: LoginForm(),
          ),
        ),
      ),
    );
  }
}
