/// Generated By XFlutter Cli.
///
/// more info: https://xflutter-cli.aghiadodeh.com
import 'package:flutter/material.dart';
import 'package:xflutter_cli_example/ui/core/layouts/base_scroll_view.dart';
import "package:xflutter_cli_example/ui/widgets/instance/instance_builder.dart";
import '../../../resources/dimensions/dimensions.dart';
import "../viewmodels/login_viewmodel.dart";
import 'package:xflutter_cli_example/ui/core/layouts/theme_widget.dart';

import '../widgets/login_form.dart';

class LoginMobileScreen extends StatelessWidget {
  const LoginMobileScreen({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return InstanceBuilder<LoginViewModel>(
      builder: (viewModel) {
        return ThemeWidget(
          builder: (context, theme) {
            return const BaseScrollView(
              child: Padding(
                padding: EdgeInsets.symmetric(horizontal: towUnits, vertical: threeUnits),
                child: LoginForm(),
              ),
            );
          },
        );
      },
    );
  }
}
