/// Generated By XFlutter Cli.
/// 
/// more info: https://xflutter-cli.aghiadodeh.com
/// 
/// state managment for UI
/// 
/// store and manage your liveData in [HomeParams].
import "home_params.dart";
import 'package:lazy_evaluation/lazy_evaluation.dart';

class HomeViewModel { 
  final _params = Lazy(() => HomeParams());
  HomeParams get params => _params.value;
}
