/// Generated By XFlutter Cli.
///
/// more info: https://xflutter-cli.aghiadodeh.com
///
/// state management for UI
///
/// store and manage your liveData in [HomeParams].
import 'package:flutter/material.dart';
import 'package:xflutter_cli_example/network/config/logger.dart';

import "home_params.dart";
import 'package:lazy_evaluation/lazy_evaluation.dart';
import 'package:xflutter_cli_example/viewmodels/base_viewmodel.dart';

class HomeViewModel extends BaseViewModel {
  final _params = Lazy(() => HomeParams());
  HomeParams get params => _params.value;

  @override
  void onInit() {
    super.onInit();
    logger("allocated in memory", name: "HomeViewModel");
  }

  @override
  void onReady() {
    super.onReady();
    logger("Ready", name: "HomeViewModel");
  }

  @override
  void onDispose() {
    logger("Disposed", name: "HomeViewModel");
    super.onDispose();
  }
}
