/// Generated By XFlutter Cli.
/// 
/// more info: https://xflutter-cli.aghiadodeh.com
import 'package:flutter/material.dart';
import 'package:flutterx_live_data/flutterx_live_data.dart';
import 'package:xflutter_cli_example/models/ui_models/ui_message.dart';

class BaseParams {
  /// request in progress
  final MutableLiveData<bool> loading = MutableLiveData(initialValue: false);

  /// UI [SnackBar] message
  final MutableLiveData<UiMessage> uiMessage = MutableLiveData(initialValue: UiMessage());
}