/// Generated By XFlutter Cli.
/// 
/// more info: https://xflutter-cli.aghiadodeh.com

enum UiMessageState { success, error, initial }

class UiMessage {
  String? message;
  String? action;
  UiMessageState state;
  UiMessage({this.message, this.action, this.state = UiMessageState.initial});
}
