/// Generated By XFlutter Cli.
/// 
/// more info: https://xflutter-cli.aghiadodeh.com
import 'package:dio/dio.dart';
import 'package:retrofit/retrofit.dart';
import 'package:xflutter_cli_example/network/config/env.dart';
import 'package:xflutter_cli_example/models/data_models.dart';
import 'package:xflutter_cli_example/models/responses/base_response/base_response.dart';
import 'package:xflutter_cli_example/models/responses/list_response/list_response.dart';
part 'product_rest_client.g.dart';

@RestApi()
abstract class ProductRestClient {
  factory ProductRestClient(Dio dio) = _ProductRestClient;

  @POST("/product")
  Future<BaseResponse<Product>> create({
    @Body() required Map<String, dynamic> product,
    @CancelRequest() CancelToken? cancelToken,
  });

  @PUT("/product/{id}")
  Future<BaseResponse<Product>> update({
    @Path("id") required String id,
    @Body() required Map<String, dynamic> product,
    @CancelRequest() CancelToken? cancelToken,
  });

  @GET("/product")
  Future<BaseResponse<ListResponse<Product>>> findAll({
    @Query("page") required int page,
    @Query("per_page") int perPage = Env.perPage,
    @Query("search") String? query,
    @CancelRequest() CancelToken? cancelToken,
  });

  @GET("/product/{id}")
  Future<BaseResponse<Product>> findOne({
    @Path("id") required String id,
    @CancelRequest() CancelToken? cancelToken,
  });

  @DELETE("/product/{id}")
  Future<BaseResponse<dynamic>> delete({
    @Path("id") required String id,
    @CancelRequest() CancelToken? cancelToken,
  });
}
