/// Generated By XFlutter Cli.
///
/// more info: https://xflutter-cli.aghiadodeh.com
import 'package:flutter/material.dart';
import "package:xflutter_cli_example/ui/widgets/instance/instance_builder.dart";
import "../viewmodels/home_viewmodel.dart";
import 'package:xflutter_cli_example/ui/core/layouts/theme_widget.dart';

class HomeTabletScreen extends StatelessWidget {
  const HomeTabletScreen({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return InstanceBuilder<HomeViewModel>(
      builder: (viewModel) => ThemeWidget(
        builder: (context, theme) => const Center(
          child: Text("Tablet Home"),
        ),
      ),
    );
  }
}
