/// Generated By XFlutter Cli.
///
/// more info: https://xflutter-cli.aghiadodeh.com
import 'package:flutter/material.dart';
import 'package:flutterx_live_data/flutterx_live_data.dart';
import 'package:xflutter_cli_example/router/app_router.dart';
import "package:xflutter_cli_example/ui/widgets/instance/instance_state.dart";
import "./viewmodels/login_viewmodel.dart";
import 'package:xflutter_cli_example/ui/widgets/loaders/live_data_loader.dart';
import 'package:xflutter_cli_example/ui/core/responsive/screen_type_layout.dart';
import 'mobile/login_mobile_screen.dart';

import 'tablet/login_tablet_screen.dart';
import 'package:xflutter_cli_example/ui/core/layouts/base_scaffold.dart';

import "package:auto_route/auto_route.dart";

@RoutePage(name: "login")
class LoginScreen extends StatefulWidget {
  const LoginScreen({Key? key}) : super(key: key);

  @override
  State<LoginScreen> createState() => _LoginScreenState();
}

class _LoginScreenState extends State<LoginScreen> with InstanceState<LoginScreen, LoginViewModel>, ObserverMixin {
  @override
  void observeLiveData(observer, viewModel) {
    // navigate to [HomeScreen] when login success
    viewModel.params.result.observe(observer, (value) {
      if (value) appRouter.replace(const Home());
    });
  }

  @override
  Widget screen(context, viewModel) {
    return Stack(
      children: [
        BaseScaffold(
          builder: (context, theme) => const SafeArea(
            child: ScreenTypeLayout(
              mobile: LoginMobileScreen(),
              tablet: LoginTabletScreen(),
            ),
          ),
        ),
        LoadingListenerWidget(loading: viewModel.baseParams.loading),
      ],
    );
  }

  @override
  LoginViewModel registerInstance() => LoginViewModel();
}
