/// Generated By XFlutter Cli.
///
/// more info: https://xflutter-cli.aghiadodeh.com
import 'package:xflutter_cli_example/ui/screens/login/login_screen.dart';
import 'package:xflutter_cli_example/ui/screens/home/home_screen.dart';
import 'package:auto_route/auto_route.dart';

part 'app_router.gr.dart';

@AutoRouterConfig(replaceInRouteName: 'Page,Route,Screen')
class AppRouter extends _$AppRouter {
  @override
  List<AutoRoute> get routes => [
        AutoRoute(path: '/login', page: Login.page, initial: true),
        AutoRoute(path: '/home', page: Home.page),
      ];
}

final appRouter = AppRouter();
