/// Generated By XFlutter Cli.
///
/// more info: https://xflutter-cli.aghiadodeh.com
import 'package:get_it/get_it.dart';

/// create a global class instance
void registerSingleton<T extends Object>(T instance, {String? instanceName}) {
  try {
    GetIt.I.registerSingleton<T>(instance, instanceName: instanceName);
  } catch (_) {
    /// avoid register more than one time.
  }
}

/// get the global instance
T getSingleton<T extends Object>({String? instanceName}) {
  return GetIt.I.get<T>(instanceName: instanceName);
}

/// remove singleton instance
Future<void> unregisterSingleton<T extends Object>({String? instanceName}) async {
  await GetIt.I.unregister<T>(instanceName: instanceName);
}

bool isRegistered({String? instanceName}) {
  return GetIt.I.isRegistered(instanceName: instanceName);
}
