/// Generated By XFlutter Cli.
/// 
/// more info: https://xflutter-cli.aghiadodeh.com
class Env {
  static const localhost = "http://192.168.1.8:3000";
  static const stagingUrl = "https://www.staging.com";
  static const liveUrl = "https://www.domain.com";

  static const baseUrl = stagingUrl;

  static const apiUrl = "$baseUrl/api";

  /// pagination
  static const perPage = 15;
}
