/// Generated By XFlutter Cli.
///
/// more info: https://xflutter-cli.aghiadodeh.com
import 'package:dio/dio.dart';
import 'package:get_it/get_it.dart';
import 'package:xflutter_cli_example/network/authentication_manager.dart';
import 'package:xflutter_cli_example/ui/core/events/bus_events.dart';
import 'logging_interceptor.dart';

/// Config Http Options
Future<void> httpConfig() async {
  await _httpClientConfig();
}

/// Config Http globally
///
/// Add "Authorization" in header to every request sent,
///
/// Add Log on console for see (Request/Response) details.
_httpClientConfig() {
  GetIt.I.registerSingleton<Dio>(Dio()
    ..interceptors.add(
      InterceptorsWrapper(
        onRequest: (request, handler) async {
          var headers = {
            'Accept': 'application/json',
            'format': 'json',
            'Authorization': 'Bearer ${await AuthenticationManager.token()}',
          };
          request.headers.addAll(headers);
          request.connectTimeout = 30000;
          request.receiveTimeout = 30000;
          handler.next(request);
        },
        onError: (error, handler) async {
          if (error.response?.statusCode == 401 || error.response?.statusCode == 403) {
            eventBus.fire(const UnauthorizedEvent());
          }
          handler.next(error);
        },
        onResponse: (response, handler) {
          handler.next(response);
        },
      ),
    )
    ..interceptors.add(LoggingInterceptor()));
}
