/// Generated By XFlutter Cli.
/// 
/// more info: https://xflutter-cli.aghiadodeh.com
import 'dart:developer' as developer;
import 'package:flutter/foundation.dart';

void logger(String message, {String? name}) {
  if (kDebugMode) {
    developer.log(message, time: DateTime.now(), name: name ?? "Debug");
  }
}