/// Generated By XFlutter Cli.
///
/// more info: https://xflutter-cli.aghiadodeh.com

import 'package:isar/isar.dart';
import 'package:xflutter_cli_example/models/data_models.dart';
part 'user.g.dart';

@collection
class IsarUser {
  Id? isarId;
  String? createdAt;
  String? name;
  String? avatar;
  String? country;
  String? city;
  String? company;
  @Index(unique: true, replace: true)
  String? id;
  IsarUser({
    this.isarId,
    this.createdAt,
    this.name,
    this.avatar,
    this.country,
    this.city,
    this.company,
    this.id,
  });
}

extension IsarUserUtils on IsarUser {
  User fromIsar() {
    return User(
      createdAt: createdAt,
      name: name,
      avatar: avatar,
      country: country,
      city: city,
      company: company,
      id: id,
    );
  }
}

extension UserUtils on User {
  IsarUser toIsar() {
    return IsarUser(
      createdAt: createdAt,
      name: name,
      avatar: avatar,
      country: country,
      city: city,
      company: company,
      id: id,
    );
  }
}
