/// Generated By XFlutter Cli.
/// 
/// more info: https://xflutter-cli.aghiadodeh.com
/// more info for responsive: https://www.filledstacks.com/post/building-a-responsive-ui-architecture-in-flutter
enum DeviceScreenType { mobile, tablet, desktop }
