/// Generated By XFlutter Cli.
/// 
/// more info: https://xflutter-cli.aghiadodeh.com
/// more info for responsive: https://www.filledstacks.com/post/building-a-responsive-ui-architecture-in-flutter
import 'package:flutter/material.dart';

class OrientationLayout extends StatelessWidget {
  final Widget unsetWidget = const Scaffold(body: Center(child: Text('OrientationLayout')));
  final Widget? landscape;
  final Widget? portrait;
  const OrientationLayout({
    Key? key,
    this.landscape,
    this.portrait,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    var orientation = MediaQuery.of(context).orientation;
    if (orientation == Orientation.portrait) {
      return portrait ?? landscape ?? unsetWidget;
    }
    return landscape ?? unsetWidget;
  }
}
