/// Generated By XFlutter Cli.
///
/// more info: https://xflutter-cli.aghiadodeh.com
///
/// declare and manage viewModel-liveData variables.
///
/// see: https://pub.dev/packages/flutterx_live_data
///
/// more details: https://medium.com/@aghiadodeh/flutter-live-data-tutorial-4c65f1b7ff5e

import 'package:xflutter_cli_example/models/forms/formz_email.dart';
import 'package:flutterx_live_data/flutterx_live_data.dart';
import 'package:xflutter_cli_example/models/forms/formz_password.dart';

class LoginParams {
  /// notify ui that login response handled
  final MutableLiveData<bool> result = MutableLiveData(initialValue: false);

  /// Login password
  final MutableLiveData<FormzPassword> password = MutableLiveData(initialValue: const FormzPassword.pure());

  /// Login mail
  final MutableLiveData<FormzEmail> mail = MutableLiveData(initialValue: const FormzEmail.pure());
}
