/// Generated By XFlutter Cli.
///
/// more info: https://xflutter-cli.aghiadodeh.com
///
/// state managment for UI
///
/// store and manage your liveData in [LoginParams].
import "login_params.dart";
import 'package:lazy_evaluation/lazy_evaluation.dart';

import 'package:flutterx_live_data/flutterx_live_data.dart';
import 'package:xflutter_cli_example/models/forms/formz_email.dart';
import 'package:xflutter_cli_example/models/forms/formz_password.dart';

class LoginViewModel {
  final _params = Lazy(() => LoginParams());
  LoginParams get params => _params.value;

  /// update [LoginParams] some [FormzEmail] variable.
  void formzEmailChanged(MutableLiveData<FormzEmail> attr, String value) {
    final newValue = FormzEmail.dirty(value);
    attr.postValue(newValue);
  }

  /// update [LoginParams] some [FormzPassword] variable.
  void formzPasswordChanged(MutableLiveData<FormzPassword> attr, String value) {
    final newValue = FormzPassword.dirty(value);
    attr.postValue(newValue);
  }
}
